import {Box} from "../../Shared/box";

export const data: Box [] = [
  {
    state: 0,
    href: '',
    text: [
      {
        header: 'Facilities for Girls',
        body: `<h3>Empowerment of women</h3>
                        <p>The extent of empowerment of women in the national hierarchy is determined largely by the three factors – her economic, social and political identity and their weightage. These factors are deeply intertwined and interlinked with many cross cutting linkages which imply that if efforts in even one dimension remain absent or weak, outcomes and momentum generated by the other components cannot be sustained as they will not be able to weather any changes or upheavals. It is only when all the three factors are simultaneously addressed and made compatible with each other can the woman be truly empowered. Therefore for holistic empowerment of the woman to happen - social, economic and political aspects impacting a woman’s life must converge effectively.
                        </p>

                        <h3>Constitutional provisions</h3>
                        <p>Women as an independent group constitute 48% of the country’s total population as per the 2001 Census. The importance of women as a important human resource was recognised by the Constitution of India which not only accorded equality to women but also empowered the State to adopt measures of positive discrimination in their favour. A number of Articles of the Constitution specially reiterated the commitment of the constitution towards the socio economic development of women and upholding their political right and participation in decision making.
                        </p>
         `
      }
    ],
    link: [],
    pdf: [
      {
        "name": 'Girl Child XI Five Year Plan',
        "href": '',
      },
      {
        "name": 'Woman Empowerment',
        "href": '',
      },
      {
        "name": 'Ministry of Women and Child Development',
        "href": '',
      }
    ]
  }
];
